### ISSUE TITLE
sudo ./scripts/install-sgx.sh true true true false not working

### ISSUE THREAD

**Issue by 0xPranjl** [scrtlabs/SecretNetwork#1061]
i was doing manual set up and following steps written but while executing sudo ./scripts/install-sgx.sh true true true false  i am getting this error sudo: ./scripts/install-sgx.sh: command not found

**Comment by eshelB** [comment]
Are you running that command from the root directory of the project?
Are you in master branch?
Do you see the `install-sgx.sh` file under `scripts` folder?

**Comment by 0xPranjl** [comment]
yes 
![asd](https://user-images.githubusercontent.com/79030501/183255998-052bcf52-cfab-40d4-a23d-a5f35b38d148.png)

**Comment by 0xPranjl** [comment]
install-sgx.sh is also present in script directory
![asx](https://user-images.githubusercontent.com/79030501/183256109-acba1f6b-08c5-41dc-8ba1-435f43127841.png)

**Comment by eshelB** [comment]
try chmod +x

**Comment by 0xPranjl** [comment]
yes it worked thanks

**Comment by Cashmaney** [comment]
I added that to the docs for clarity. Thanks for opening the issue @0xPranjl
