### ISSUE TITLE
Ledger Nano S Plus not detected by secretd

### ISSUE THREAD

**Issue by colossus-digital** [scrtlabs/SecretNetwork#1161]
`secretd` with Ledger support is not detecting Ledger Nano S Plus. 

```
secretd keys add key_name --ledger
Error: failed to generate ledger key: failed to retrieve device: ledger nano S: no ledger connected
```

The device has the latest firmware, is unlocked and the Secret app opened. The device is also listed using the `lsusb` command 

```
lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 2c97:5011 Ledger Nano S Plus <--------
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

```

Look at that, i think it's the same issue (now solved with the gaiad v7.0.3) [gaiad_issue_1630](https://github.com/cosmos/gaia/issues/1638)

**Comment by assafmo** [comment]
Hi, this is going to be fixed on the September 20 upgrade

https://github.com/scrtlabs/SecretNetwork/pull/1123
