### ISSUE TITLE
Nested Submsg error

### ISSUE THREAD

**Issue by xucito** [scrtlabs/SecretNetwork#1191]
When nesting a submessage inside another submessage the second submessage throws error
`failed to execute message; message index: 0: dispatch: submessage: dispatch: submessage: Execution error: Enclave: failed to deserialize data: reply to contract failed`

The structure looks is
`contract-A--submessage --> contract-B--submessage --> contract-C`

When calling contract-C via submessage from contract-A there is no issues.

Tested on ghcr.io/scrtlabs/localsecret:v1.4.0-beta.11

**Comment by assafmo** [comment]
Can you share the code please?

**Comment by xucito** [comment]
You can run the integration test here to see the error.

https://github.com/securesecrets/shadeswap/commit/05ca3553b3aae6a48a37c96140acff50160d9d42

The error occurs within amm_pair when it calls instantiate on lp_token as a submessaged

`factory > submessage > amm_pair > submessage > lp_token`

To run the tests
```
server start
```
on another terminal 
```
server-connect
make && make integration-tests
```

When you change it to 

`factory > submessage > amm_pair > message > lp_token`

no issues

**Comment by Cashmaney** [comment]
cc @liorbond

**Comment by liorbond** [comment]
@xucito Thank you for reporting this issue, I was able to reproduce this issue as well, having a look into it. Will update as soon as I will have an idea of what happens here

**Comment by xucito** [comment]
No problems, I also think there is an issue with
`contract-A--submessage --> contract-B--message--> contract-C`
Was encountering a transaction signer verification error but I haven't had the time to double check.
