### ISSUE TITLE
Msg on Sub Msg Reply fails to validate

### ISSUE THREAD

**Issue by xucito** [scrtlabs/SecretNetwork#1201]
When nesting a msg inside another submessage's reply the message throws error
failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: submessages: Execution error: Enclave: failed to validate transaction: execute contract failed: reply to contract failed

The structure looks is
contract-A--submessage --> contract-B-- reply --> contract-A --> Msg --> Err

Tested on ghcr.io/scrtlabs/localsecret:v1.4.0-beta.14 & v1.4.1-beta.8

To replicate:
https://github.com/securesecrets/shadeswap/commit/7c5f9d676fe3dbe878d80cd1fddcc678ebab315a

To run the test

`server start`
on another terminal
```
server-connect
make && make integration-tests
```

**Comment by xucito** [comment]
Apologies, this was actually an issue with the contract. Closing

**Comment by assafmo** [comment]
LOL you gave me a scare there :sweat_smile:
