### ISSUE TITLE
Sub Msg Reply Chain Fails if last response has .add_attributes

### ISSUE THREAD

**Issue by xucito** [scrtlabs/SecretNetwork#1235]
When nesting a msg where the response overrides the data with add_attributes inside another submessage's reply it throws a validation error.

failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: submessages: Execution error: Enclave: failed to validate transaction: execute contract failed: reply to contract failed

The structure looks like
contract-A--submessage --> contract-B--> msg (uses add_attribute)

Tested on ghcr.io/scrtlabs/localsecret:v1.4.0-beta.14 & v1.4.1-beta.8

To replicate:
https://github.com/securesecrets/shadeswap/commit/7c5f9d676fe3dbe878d80cd1fddcc678ebab315a

To run the test

`server start`
on another terminal
```
server-connect
make && make integration-tests
```

If you remove the add_attribute the test will pass (like the following)
https://github.com/securesecrets/shadeswap/commit/ce38703ff1ff636f49619c2023a3eebc866d735d

**Comment by liorbond** [comment]
Hey @xucito. Thank you for reporting the issue, Ill have a look now and will update here for any progress.

**Comment by assafmo** [comment]
> contract-A--submessage --> contract-B--> msg (uses add_attribute)

Hi, we're unable to reproduce the bug. This^ flow works for us. Can you provide a more detailed flow of events?

**Comment by xucito** [comment]
You can try my project, it might be a more specific use-case I thought it was the above from testing.

Exactly flow in the linked DApp is

contract A -> Sub Msg (SNIP 20 Send) --> SNIP20 Contract --> Msg (via Receiver Callback) --> Contract B --> Reply ( applies add_attribute)

**Comment by liorbond** [comment]
Hey,
Was able to reproduce the bug and have a fix for it. Is there any chance you can use the following local secret: https://github.com/scrtlabs/LocalSecret/pkgs/container/localsecret/48072123?tag=beta-nested-attributes to make sure it solve the bug for you?
