### ISSUE TITLE
Add checking of "required features"

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#280]
> Add checking of "required features" like they do in cosmwasm_vm

@reuvenpo could you elaborate on this?

**Comment by reuvenpo** [comment]
CosmWasm wanted to support the idea chains providing extensions to the base interfaces that they defined. To allow that in a way that will allow maximum cross-chain compatibility, they defined a standard interface for declaring which extensions a contract requires. The idea, as i understand it, is that chains won't run contracts that require extensions that they do not support.
Most of the related code is here:
https://github.com/CosmWasm/cosmwasm/blob/b971c037a773bf6a5f5d08a88485113d9b9e8e7b/packages/vm/src/features.rs
but i recommend checking out and browsing their repositories (`cosmwasm` and `go-cosmwasm`) to get the full picture. Maybe even ask Ethan and Simon directly.

**Comment by assafmo** [comment]
This is already happening
