### ISSUE TITLE
Build a contract example catalog

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/SecretNetwork#286]
- [ ] Small examples with good code comments and docs
  - [ ] a simple constructor
  - [ ] using the storage
  - [ ] preserving privacy examples (#247)
- [ ] Create a similar script to `react-create-app` for quick start for contract devs

**Comment by reuvenpo** [comment]
This issue, as described is not complete yet, but much of it exists in https://github.com/enigmampc/secret-template

**Comment by assafmo** [comment]
https://github.com/SecretFoundation/awesome-secret#reference-contracts
