### ISSUE TITLE
Build a GUI for BattleSheep

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/SecretNetwork#401]
"[Battle Sheep](https://github.com/reuvenpo/secret-battlesheep)" is an implementation of the classic Battleship game as a secret contract 🎉

At the moment this is only an implementation of the secret contract part, without a GUI. We would welcome community contributions to build a GUI for Battle Sheep

### UPDATE February 2021:
In the thread below fmrsoares talked about implementing this, but seems to have dropped the project. Feel free to pick it up :)

**Comment by fmrsoares** [comment]
Hello, I'm looking to contribute to Secret Network. (never contributed to any open source project before :x)
I have some experience creating front-ends in React and already messed around with secret contracts on the testnet, so, if this task is still available I would love to start take a stab at this on my spare time! ;)

**Comment by cankisagun** [comment]
@fmrsoares very excited to see your message :) Yes you can work on the GUI for battleship! Also looping in @reuvenpo who built the secret contract for the battleship!

**Comment by fmrsoares** [comment]
What is the best way to contact @reuvenpo? I'm trying to test the battle sheep contract but after correctly instantiated on the testnet or devnet if i try to do any action (like new_game), I reach this error:
     `execute contract failed: Execution error: Enclave: the contract panicked: failed to execute message; message index: 0`

**Comment by reuvenpo** [comment]
Oh no, that's gonna be annoying to debug :D
I'm `reuven.podmazo` on https://chat.scrt.network .
You can start by PMing me there :)
If you have / prefer telegram I can PM you my handle on https://chat.scrt.network

**Comment by cankisagun** [comment]
@fmrsoares , are you still interested in working on this issue? If you have started, it would be great to get an update on the progress. Now we have the mainnet up, we can upload this game :)

**Comment by reuvenpo** [comment]
@fmrsoares and I have been working 1-4 hours a week working out some bugs in the code as he's learning to interact with the contracts, and how to work with Rust :)
