### ISSUE TITLE
secretJS docs

### ISSUE THREAD

**Issue by jlwaugh** [scrtlabs/SecretNetwork#409]
related to issues #372 and #399

improving [secretJS documentation](https://build.scrt.network/dev/secret-js.html)

current folder ~ [docs/dev/secret-js.md](https://github.com/enigmampc/SecretNetwork/blob/master/docs/dev/secret-js.md)

updating [npm package](https://www.npmjs.com/package/secretjs)

goal: "create-secret-app"

**Comment by assafmo** [comment]
> updating npm package

This is done automatically by publishing the package to NPM, it takes the README.md from the package root (I.e. https://github.com/enigmampc/SecretNetwork/blob/develop/cosmwasm-js/packages/sdk/README.md)

**Comment by assafmo** [comment]
> goal: "create-secret-app"

This is unrelated IMO and is mostly solved by this: https://github.com/enigmampc/secret-template

**Comment by assafmo** [comment]
Also, we might be able to largely generate these docs from code comments like I did in this repo: https://github.com/assafmo/OrdernetAPI#readme
