### ISSUE TITLE
Dark pool

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/SecretNetwork#525]
[Dark pool](https://www.investopedia.com/terms/d/dark-pool.asp#:~:text=Dark%20pools%20are%20a%20type,for%20a%20buyer%20or%20seller.) is trading system that's primarily used for large orders. The order books and offers in a dark pool are hidden from the participants and are only available to the administrator of the dark pool.

With secret contracts, we have the opportunity to create decentralized, trust-less dark pools by building a privacy preserving order book and swap system.

This project is an extension of Secret Auctions (Issue #524 ) as an order books is practically a two-sided auction.

This approach requires an on-chain order-book, which is advantageous to bootstrap liquidity by offering liquidity incentives

**Comment by mohammedpatla** [comment]
@CarterLWoetzel

**Comment by lzy-v** [comment]
i would be interesting in helping - hedge fund background

**Comment by cankisagun** [comment]
pls reach out to me on discord can_enigma#0743
