### ISSUE TITLE
Fix occasional failure to register with Azure docker image

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#603]
The current docker image `enigmampc/secret-network-node:v1.0.0-mainnet` waits for 5 seconds after registering. Occasionally this means that the command doesn't get registered on-chain in time. The script is already update with a 10 second wait, just need to rebuild the image (without changing the enclaves/recompiling the code) and reupload the image (without changing the name, otherwise we'd have to update the azure offering as well - which takes a few days)

**Comment by assafmo** [comment]
Is this still relevant?
