### ISSUE TITLE
When trying to instantiate a non-existent code-id cli returns silly error

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#605]
```
./secretcli-linux-amd64 tx compute instantiate 128 '{}' --label yo --from t1
ERROR: unexpected end of JSON input
```
🙄

**Comment by assafmo** [comment]
LOL this is still a thing.

**Comment by Cashmaney** [comment]
Haha. Bumping this so we finally fix this

**Comment by MustafaPicakci** [comment]
Hi! 
I'm still getting this error when i trying to instantiate my contract on local-secret docker container.

How can i get over this?

**Comment by liorbond** [comment]
https://github.com/cosmos/cosmos-sdk/pull/12981
