### ISSUE TITLE
Add crypto primitives to secret toolkit

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#609]
Secret toolkit could use primitives for re-use in contracts, instead of copying or writing from scratch

* Hashing - https://github.com/enigmampc/secretSCRT/blob/6076fbf54725f5530b39e9b7b987243190c9a1df/src/rand.rs#L6
* RNG - https://github.com/enigmampc/secretSCRT/blob/6076fbf54725f5530b39e9b7b987243190c9a1df/src/rand.rs#L20
* Secp256k1 Signatures - https://github.com/enigmampc/secret-vault/blob/ce8d857e52abf721318fd4db224fa1161792e071/src/sign.rs#L8

Other crypto primitives - 

* More signature types (25519)

**Comment by reuvenpo** [comment]
everything except the ed25519 algorithm has been added to the toolkit
