### ISSUE TITLE
Grouping contract

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#610]
Could be cool to do something like this https://github.com/regen-network/cosmos-modules/tree/master/incubator/group as a secret contract. Since we have integration between contracts and the gov module this could enable secret voting for groups

**Comment by reuvenpo** [comment]
This is similar to this:
https://github.com/levackt/voting-app/tree/secret

**Comment by Cashmaney** [comment]
This is pretty much CW4 - https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw4-group
