### ISSUE TITLE
Remove unnecessary logs from dev image

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#613]
The docker dev image (built with `make build-dev-image`) contains a lot of junk that a contract developer doesn't care about. 

1. Too many logs - the image compiles with all the trace logs, which are just for the core developers. A contract developer only cares about stuff that pertains to his contract

2. Logging encrypted data - Logs like "reading scrambled key [12, 222, ...]" are kind of useless, and serve to make the logs harder to read. Better is to omit the encrypted stuff, or even to just print the plain text data

**Comment by toml01** [comment]
A quick solution would be to compile with a higher log level. Logs from `debug` and higher should be somehow relevant for contract development (as described [here](https://github.com/enigmampc/SecretNetwork/issues/491#issuecomment-683429093)), but some are probably unnecessary.

**Comment by reuvenpo** [comment]
This is assigned to @PumpkinSeed
