### ISSUE TITLE
secretcli: Create a Windows, Mac & Linux installers

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/SecretNetwork#615]
As for Linux, there's one for `secretd` that also includes `secretcli`: https://github.com/enigmampc/SecretNetwork/blob/865f7127b5f05e75f5d501c5aa1a4ef7e7bceae0/Makefile#L146-L175 so we just need to create one without `secretd` and make sure the package names don't conflict.

Also see the Makefile rules for building secretcli: https://github.com/enigmampc/SecretNetwork/blob/865f7127b5f05e75f5d501c5aa1a4ef7e7bceae0/Makefile#L132-L142

**Comment by Cashmaney** [comment]
We might need to register with Microsoft/Apple to create installers?

**Comment by assafmo** [comment]
> We might need to register with Microsoft/Apple to create installers (to have them signed, anyway)?

Maybe...? I'm sure there are ways to create installers without signing the executables.
