### ISSUE TITLE
Upgrade enclave signature validation

### ISSUE THREAD

**Issue by toml01** [scrtlabs/SecretNetwork#648]
Upgrade existing code to the new Stargate interfaces.
Keep [this](https://github.com/cosmos/cosmos-sdk/blob/v0.40.0-rc1/types/tx/tx.pb.go#L32-L42) struct in mind (or something equivalent in the final release)

**Comment by reuvenpo** [comment]
I believe this is mostly done, i want to check that multisig works correctly though because i don't remember testing it.

**Comment by reuvenpo** [comment]
It works now:
https://github.com/enigmampc/SecretNetwork/pull/809
