### ISSUE TITLE
Remove cosmwasm "iterator" feature

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#677]
We don't implement "db_scan", so usage of iterator functions will fail

cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.0", features = ["iterator"] }

Should be not be allowed

**Comment by assafmo** [comment]
Is this for v1.1.x?

**Comment by reuvenpo** [comment]
We originally decided to keep the interfaces to reduce friction for people porting contracts from the original cosmwasm runtime.
That being said... I think that a compilation error is probably clearer than a runtime error you'll see much later.

related to https://github.com/enigmampc/SecretNetwork/issues/275
