### ISSUE TITLE
Private order book - Limit order contract for secretAMM

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/SecretNetwork#699]
This feature depends on SecretAMM, which is expected to be completed in January 2021. However building a private order book is a pre-requisite to have a fully private DEX (dark pool #525).

The goal is to create a limit orders for secretAMM. This involves building a secret contract that acts as an order book.
Secret contract holds bid info (price / quantity) and funds. It also queries secretAMM prices. When there's an offer in the money, limit order contract trades on the AMM on behalf of the user. This would be the story line:
- Alice wants to buy 10 secretETH at P= 500DAI / ETH.
- Alice sends inputs of bid, quantity and price (_buy_, _10 secretETH_, 500DAI/ETH) to the secret contract. Bob can do the same etc. Let’s call this limit order contract. We’d be creating an order book here for different asset pairs
- When limit order contract receives the bids, it needs to sort them based on price and quantity to create a secret order book
- Limit order contract queries AMM prices and depths
- If the price of the secretETH goes below 500, secret contract automatically starts buying secretETH for Alice as long as the price is <= 500DAI/ETH on the AMM.
- Purchased secretETH is sent to Alice’s address as soon as trades take place (or Alice can withdraw secretETH from the contract)…

**Comment by cankisagun** [comment]
Here's pine.finance that works on limit orders on Uniswap https://medium.com/@pine_eth/pine-finance-an-amm-orders-engine-525fe1f1b1eb

**Comment by RandomUser42069** [comment]
This seems very interesting. Was thinking on an architecture for this service but the first question comes to mind is the fact that the Limit Order Contract would need to querie constantly the AMM prices and depths.
How would one do this in a descentralized way without one external backend server doing the requests?

**Comment by assafmo** [comment]
It's hard to trigger events in a decentralized way. I think a good start is a decentralized (front running resistant) order book with centralized triggers.

You can incentivize people to send triggers but this will eat away your yield.

**Comment by cankisagun** [comment]
I was thinking of a model similar to Maker CDP - if a CDP is in default then any user can call the contract to collect the collateral. The economics of Maker CDP is more attractive than receiving 1 SCRT to call a limit order book contract, that's true. 

I agree with Assaf, I think we can build a centralized triggering system that would know at which prices to trigger the secret contract that holds the order book. However the centralized triggering system wouldn't know the order type (buy / sell) or amount.

Is this something you'd be interested to work on @RandomUser42069

**Comment by RandomUser42069** [comment]
Well, I like the ideia but dont know if I would be able to do it as I'm still gaining experience on secret network + rust.

This seems quite complex and I have limited free time.
But seems like a great project to do some useful stuff.

I can probably start developing it and ask multiple questions on discord as I'm already doing :sweat_smile:

**Comment by assafmo** [comment]
Go for it! We're here for you if you need anything.

**Comment by RandomUser42069** [comment]
Hey! 

So before starting developing, I did some diagrams [here](https://github.com/RandomUser42069/secret-amm-limit-orders/blob/master/docs/SecretAMM%20Limit%20Orders%20-%20Architecture%20and%20Flows.png) with the flows for the basic functions that I think are relevant for this project.

Would love some feedback, if this is the correct path or something does not make sense on the flows :innocent:

**Comment by assafmo** [comment]
Looks like a good start!
I'd start by coding the happy path and going from there. :relaxed:

**Comment by cankisagun** [comment]
WIP repo for anyone who'd like to contribute: https://github.com/ThatRand0mUser/secret-amm-limit-orders
