### ISSUE TITLE
secretcli API/doc

### ISSUE THREAD

**Issue by SecretBeam** [scrtlabs/SecretNetwork#702]
>secretcli keys add \<key-alias\>

The purpose of \<key-alias\> is not described (type of input, what it does)
I was told it is a string used to ID keys that is saved locally
It would be interesting to know where, depending on the OS

>secretcli keys add --recover

This command line as is is not valid as it seems to expect a \<key-alias\> and therefore the recovering is saved somewhere on the computer

For all these commands it would be great to be able to let the \<key-alias\> be optional and in case it's not provided simply print the keys without saving it imo

>::: danger Warning We strongly recommend NOT using the same passphrase for multiple keys. The Tendermint team and the Interchain Foundation will not be responsible for the loss of funds. :::

Define "passphrase" as this word has not been used before

**Comment by assafmo** [comment]
Cc @dylanschultzie
