### ISSUE TITLE
Staking based fixed income product

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/SecretNetwork#706]
Build a fixed income product by leveraging existing yield opportunities in Secret Network like staking or based on DeFi products like options.

_Staking based fixed income product_
Using staking yield, build a fixed income investment product either for SCRT or other ETH assets. For assets besides SCRT, this would require taking a FX risk between SCRT and the asset used in the product. 
staking derivatives (issue #705)

_Staking based SCRT FX Swaps / Fixed income on ETH assets_
Summary: Create a speculative product that replicates MKR CDP concept to provide a tool to: 
- Go long on SCRT + earn staking rewards while shorting stable coins
- Earn fixed interest income on stable coins

Alice has SCRT and Stake for ~30% return. (With SecretAMM Alice can start with ETH / DAI, get secret ETH / DAI, swap to SCRT to earn yield as well). Now, what if Bob wants to hold DAI and I can still get 10% interest? This product creates a liquidity pool for Alice&Co., where Alice&Co. is bullish on SCRT and will:
- go short on DAI with 10% interest promise to DAI holder
- go long on SCRT and receive ~300% interest in SCRT

This product requires:
- a mechanism for liquidating the SCRT at different price points to ensure the fixed yield in DAI can be paid
- introduce an insurance pool (over-collateralized SCRT pool), to ensure that Bob can receive his fixed interest rate even if the price of SCRT goes down wrt DAI.

With currency risk, comes this idea of speculation. The idea of taking currency risk on an asset that you believe in is what made MKR / CDP what it is today - i.e. ppl would collateralize ETH, get DAI, buy more ETH b/c they were bullish on ETH over DAI. That’s something we can replicate with SCRT. An advantage we have over ETH is SCRT earns income (staking) whereas ETH does not. At this point the inflation in the network becomes very interesting b/c the higher the inflation, the higher the arbitrage opportunity.

If interested in collaborating in this project please reach out to me for a detailed discussion

**Comment by Mehmetbatmaz** [comment]
H
