### ISSUE TITLE
(Error) secretcli keys add

### ISSUE THREAD

**Issue by neocrash** [scrtlabs/SecretNetwork#726]
Could you take a look at this errors?

-Run command below
secretcli keys add KEYNAME--recover
or secretcli keys add KEYNAME

But it is working properly with --keyring-backend file. 

-Error
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/enigmampc/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x1471750, 0x1471748, 0xc000023800, 0x1, 0x1, 0xc000023810, 0x1, 0x1, 0x1610a40, 0xc000ba65d0, ...)        /go/pkg/mod/github.com/enigmampc/cosmos-sdk@v0.9.0-scrt/crypto/keys/keyring.go:479 +0x38c
github.com/enigmampc/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x1471750, 0x1471748, 0xc000023800, 0x1, 0x1, 0xc000023810, 0x1, 0x1, 0x1610a40, 0xc000ba65d0, ...)
        /go/pkg/mod/github.com/enigmampc/cosmos-sdk@v0.9.0-scrt/crypto/keys/keyring.go:465 +0x189
github.com/enigmampc/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x1471750, 0x1471748, 0xc000023800, 0x1, 0x1, 0xc000023810, 0x1, 0x1, 0x15fd880, 0xc000bd31d0, ...)
        /go/pkg/mod/github.com/enigmampc/cosmos-sdk@v0.9.0-scrt/crypto/keys/keybase_base.go:171 +0x192
github.com/enigmampc/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
        /go/pkg/mod/github.com/enigmampc/cosmos-sdk@v0.9.0-scrt/crypto/keys/keyring.go:107
github.com/enigmampc/cosmos-sdk/client/keys.RunAddCmd(0xc000b5b600, 0xc000b915a0, 0x1, 0x2, 0x1627520, 0xc000bd3180, 0xc00002c3c0, 0xc000e27c10, 0xb2a797)
        /go/pkg/mod/github.com/enigmampc/cosmos-sdk@v0.9.0-scrt/client/keys/add.go:277 +0xe20
github.com/enigmampc/cosmos-sdk/client/keys.runAddCmd(0xc000b5b600, 0xc000b915a0, 0x1, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/enigmampc/cosmos-sdk@v0.9.0-scrt/client/keys/add.go:99 +0x165
github.com/spf13/cobra.(*Command).execute(0xc000b5b600, 0xc000b91580, 0x2, 0x2, 0xc000b5b600, 0xc000b91580)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c8dc0, 0xbc1f30, 0xc0000c8dc0, 0x126a352)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000c8dc0, 0x14742f0, 0x2, 0xc000dc8ae0)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/libs/cli/setup.go:89 +0x3c
main.main()
        /go/src/github.com/enigmampc/SecretNetwork/cmd/secretcli/main.go:68 +0x38f

**Comment by toml01** [comment]
What environment are you working on?
