### ISSUE TITLE
go-cosmwasm - compilation errors

### ISSUE THREAD

**Issue by bezrazli4n0** [scrtlabs/SecretNetwork#743]
Hello, i'm trying to compile go-cosmwasm on windows, but got errors:
![изображение](https://user-images.githubusercontent.com/56516965/116731648-a3c97200-a9f2-11eb-92e4-e81870d63bf7.png)

**Comment by assafmo** [comment]
Hi @bezrazli4n0, I don't think we wrote Makefile rules for compilation on Windows.

**Comment by bezrazli4n0** [comment]
> 
> 
> Hi @bezrazli4n0, I don't think we wrote Makefile rules for compilation on Windows.

Yeah, there are no makefile for windows, but im trying to compile manualy with `cargo build --release`. Can you share dll/lib for windows?

**Comment by assafmo** [comment]
We don't have one. I think SGX on Windows has too many limitations that it just won't run our code. You are welcome to try and share your experience with us. :blush:

**Comment by bezrazli4n0** [comment]
> 
> 
> We don't have one. I think SGX on Windows has too many limitations that it just won't run our code. You are welcome to try and share your experience with us. 😊

Okay, but how secretcli is compiled and worked on windows?

**Comment by assafmo** [comment]
Closing because we since upgraded to Stargate. @bezrazli4n0 let me know if this is still an issue.
