### ISSUE TITLE
secretkeys keys parse (win) converts bytes to 'cosmos' addresses not secret ones

### ISSUE THREAD

**Issue by PFC-developer** [scrtlabs/SecretNetwork#746]
C:\>>secretcli version
1.0.4-3-g05d87a48

C:\>secretcli keys parse secret18ll5eppuazehl2uxt43x367dx3pj3jl9ytv27k
human: secret
bytes: 3FFF4C843CE8B37FAB865D6268EBCD344328CBE5

C:\>secretcli keys parse 3FFF4C843CE8B37FAB865D6268EBCD344328CBE5
formats:
- cosmos18ll5eppuazehl2uxt43x367dx3pj3jl9xwcrr2
- cosmospub18ll5eppuazehl2uxt43x367dx3pj3jl9eg5s60
- cosmosvaloper18ll5eppuazehl2uxt43x367dx3pj3jl9r6vk0e
- cosmosvaloperpub18ll5eppuazehl2uxt43x367dx3pj3jl93e44du
- cosmosvalcons18ll5eppuazehl2uxt43x367dx3pj3jl9hfl2rc
- cosmosvalconspub18ll5eppuazehl2uxt43x367dx3pj3jl9qawa8d

^^ this makes it challenging to convert back/forward from validator/account address as the bech32 checksum will be different.

**Comment by assafmo** [comment]
Hi @petes-fan-club, this is a cool feature and bug I didn't know existed!
While we fix this, you can use [this website](https://bech32.enigma.co) or [this CLI](https://github.com/enigmampc/bech32.enigma.co/releases/tag/cli) to convert between prefixes.
