### ISSUE TITLE
SecretJS: Remove obsolete @iov/crypto, @iov/encoding and @iov/utils

### ISSUE THREAD

**Issue by webmaster128** [scrtlabs/SecretNetwork#747]
- @iov/crypto [is now an alias to @cosmjs/crypto](https://github.com/iov-one/iov-core/blob/v2.5.0/packages/iov-crypto/src/index.ts), but pulls in an old CosmJS version
- @iov/encoding [is basically an alias for @cosmjs/encoding and @cosmjs/math](https://github.com/iov-one/iov-core/blob/v2.5.0/packages/iov-encoding/src/index.ts), but pulls in an old CosmJS version
- @iov/utils [is now an alias for @cosmjs/utils](https://github.com/iov-one/iov-core/blob/v2.5.0/packages/iov-utils/src/index.ts), but pulls in an old CosmJS version

By replacing the dependencies with their @cosmjs/* version you can follow current development and do not depend on the unmaintained IOV Core anymore. In all 3 cases I am not aware of any significant functional or API change since 0.20.0.

**Comment by assafmo** [comment]
Thanks for letting us know Simon! :smiling_face_with_three_hearts: 
We don't really use these for more than base64, hex and utf8 conversions, but I'll update all of them the next time I get the chance.

**Comment by webmaster128** [comment]
I'd like to remind you that `@iov/*` packages are unmaintained and thus are a threat to every application depending on the `secretjs` package. This includes Keplr and applications integrating Keplr. In the interest of the entire ecosystem, I advise you to get rid of them before it becomes a problem.

**Comment by assafmo** [comment]
Thanks for the reminder @webmaster128, we're going to migrate to `cosmjs` soon after our IBC upgrade, in about 1-2 months.

**Comment by assafmo** [comment]
Done in https://github.com/scrtlabs/secret.js, thanks @webmaster128!

**Comment by webmaster128** [comment]
secret.js as a wrapper around latest and greatest CosmJS code – that's the way!
