### ISSUE TITLE
Decide which types of cosmos messages we want to implement

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/SecretNetwork#782]
Extend [this](https://github.com/enigmampc/SecretNetwork/blob/0e4505ed75253e7ebbf6491cb22112ada48a0557/go-cosmwasm/types/msg.go?plain=1#L63-L69) and all subsequent usages, including adding them to cosmwasm-std in [here](https://github.com/enigmampc/SecretNetwork/blob/0e4505ed75253e7ebbf6491cb22112ada48a0557/cosmwasm/packages/std/src/init_handle.rs?plain=1#L17-L28) and inside the enclave in [here](https://github.com/enigmampc/SecretNetwork/blob/0e4505ed75253e7ebbf6491cb22112ada48a0557/cosmwasm/packages/wasmi-runtime/src/cosmwasm/types.rs?plain=1#L164-L175).

- [ ] x/auth
  - [ ] [MsgCreateVestingAccount](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/auth/vesting/types/tx.pb.go#L35)
- [ ] x/authz
  - [ ] [MsgExecResponse](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/authz/tx.pb.go#L77)
  - [ ] [MsgExec](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/authz/tx.pb.go#L117)
  - [ ] [MsgRevoke](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/authz/tx.pb.go#L197)
- [ ] x/bank
  - [ ] [MsgSend](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/bank/types/tx.pb.go#L34)
  - [ ] [MsgMultiSend](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/bank/types/tx.pb.go#L111)
- [ ] x/crisis
  - [ ] [MsgVerifyInvariant](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/crisis/types/tx.pb.go#L32)
- [ ] x/distribution
  - [ ] [MsgSetWithdrawAddress](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/distribution/types/tx.pb.go#L35)
  - [ ] [MsgWithdrawDelegatorReward](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/distribution/types/tx.pb.go#L112)
  - [ ] [MsgWithdrawValidatorCommission](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/distribution/types/tx.pb.go#L189)
  - [ ] [MsgFundCommunityPool](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/distribution/types/tx.pb.go#L267)
- [ ] x/evidence
  - [ ] [MsgSubmitEvidence](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/evidence/types/tx.pb.go#L36)
- [ ] x/feegrant
  - [ ] [MsgGrantAllowance](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/feegrant/tx.pb.go#L35)
  - [ ] [MsgRevokeAllowance](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/feegrant/tx.pb.go#L136)
- [ ] x/gov
  - [ ] [MsgSubmitProposal](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/gov/types/tx.pb.go#L37)
  - [ ] [MsgVote](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/gov/types/tx.pb.go#L121)
  - [ ] [MsgVoteWeighted](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/gov/types/tx.pb.go#L197)
  - [ ] [MsgDeposit](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/gov/types/tx.pb.go#L273)
- [ ] x/slashing
  - [ ] [MsgUnjail](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/slashing/types/tx.pb.go#L32)
- [ ] x/staking
  - [ ] [MsgCreateValidator](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/staking/types/tx.pb.go#L40)
  - [ ] [MsgEditValidator](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/staking/types/tx.pb.go#L121)
  - [ ] [MsgDelegate](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/staking/types/tx.pb.go#L204)
  - [ ] [MsgBeginRedelegate](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/staking/types/tx.pb.go#L282)
  - [ ] [MsgUndelegate](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0-rc2/x/staking/types/tx.pb.go#L369)

**Comment by Cashmaney** [comment]
Doesn't this depend on what we do with the cosmwasm module? (which upgrade path we choose)

**Comment by assafmo** [comment]
We're not touching the core cosmwasm module, we'll just add support for all of these messages in cosmwasm-std and in x/compute (where these messages get translated into proper cosmos messages).

Not sure if we'll implement all of these^, I just pasted all of them here for now.
