### ISSUE TITLE
Supernova-1: /reg/cons/consensus-io-exch-pubkey returns Not Implemented

### ISSUE THREAD

**Issue by jacobtjackson** [scrtlabs/SecretNetwork#828]
I'm using the supernova-1 testnet to test out creating viewing keys post-IBC. I'm using secretJS v0.10.4 (so pre-IBC) but when I try to use the `SigningCosmWasmClient` to send the contract execution tx, it fails on the call to http://LCD_SERVER:1317/reg/consensus-io-exch-pubkey (not the actual URL). Has this just not been implemented yet, or is there going to be a different route for post-IBC contract executions? For reference, here's the code I'm using: 

```
let client = new SigningCosmWasmClient(
      nodeUrl,
      this.wallet.publicAddress,
      (signBytes) => this.wallet.contractSign(signBytes),
      txEncryptionSeed,
      {
        init: {
          amount: [{ amount: "300000", denom: "uscrt" }],
          gas: "300000",
        },
        exec: {
          amount: [{ amount: "300000", denom: "uscrt" }],
          gas: "300000",
        },
      },
      BroadcastMode.Sync
    )

    const random = new Uint8Array(15);
    crypto.getRandomValues(random);
    const entropy = Buffer.from(random).toString("hex");

    let handleMsg = { create_viewing_key: {entropy: entropy} };
    // const contractAddress = 'secret1k0jntykt7e4g3y88ltc60czgjuqdy4c9e8fzek';
    let { transactionHash } = await client.execute(this.contractAddress, handleMsg);
    ```

**Comment by assafmo** [comment]
Try with secretjs@0.17.4-beta1, anything below 0.17 won't work with supernova.

**Comment by jacobtjackson** [comment]
> Try with secretjs@0.17.4-beta1, anything below 0.17 won't work with supernova.

Gotcha, I'll give that one a shot! Thanks
