### ISSUE TITLE
can i install the node in aws 

### ISSUE THREAD

**Issue by pokerstarxy** [scrtlabs/SecretNetwork#831]
aws does not support the sgx ,but the ec2 has a TEE solution called nitro enclave ,but i do not know how to Associate the node with the cloud service ?  anybody help me ?

**Comment by toml01** [comment]
Hey @pokerstarxy , SGX is currently the only supported TEE technology that Secret Network supports - therefore running a node on a different solution (such as the one you mentioned) will not work.

Here is a list of cloud vendors that support SGX: https://github.com/ayeks/SGX-hardware#cloud-vendors (this is not maintained by Enigma or the Secret Network).
You can also look for advise in our [community discord](https://discord.com/invite/SJK32GY). Check our #node-discussion or #node-support

**Comment by reuvenpo** [comment]
There is a list of known hosting and hardware solutions for the Secret Network here:
https://docs.scrt.network/node-guides/hardware-compliance.html
