### ISSUE TITLE
chat.scrt.network opens broken discord link

### ISSUE THREAD

**Issue by DougAnderson444** [scrtlabs/SecretNetwork#837]
https://github.com/scrtlabs/SecretNetwork/blob/bb33ca25bd07026faa2680367d1174e577bb188b/docs/.vuepress/config.js#L10

It leads to https://discord.com/invite/mUya9JArVa instead of https://discord.com/invite/SJK32GY

**Comment by assafmo** [comment]
@moonstash @torsecret

**Comment by moonstash** [comment]
Chat.scrt.network seems to work fine.

**Comment by assafmo** [comment]
@DougAnderson444 please confirm :pray:

**Comment by DougAnderson444** [comment]
I still get this broken link. Steps to reproduce:

goto: https://learn.scrt.network/sgx.html
in para 1., click the link [the infrastructure room](https://discord.com/invite/aCCnzq8VuR)
you'll see it leads to https://discord.com/invite/aCCnzq8VuR which is an invalid discord link :/

**Comment by moonstash** [comment]
Thanks for the clarification i thought it was being stated the chat.scrt.network url was wrong or expired. @dylanschultzie can you look into this? I dont maintain the docs anymore.

**Comment by dylanschultzie** [comment]
> Thanks for the clarification i thought it was being stated the chat.scrt.network url was wrong or expired. @dylanschultzie can you look into this? I dont maintain the docs anymore.

Yeah, that's correct. With https://github.com/SecretFoundation/docs/pull/17 being merged, `learn.scrt.network` can/should be wound down.

**Comment by dylanschultzie** [comment]
@assafmo I'd wager this can be closed once `learn.scrt.network` is wound down.

**Comment by assafmo** [comment]
Thanks @dylanschultzie, let me know.

**Comment by reuvenpo** [comment]
@dylanschultzie I think we should set a redirect from learn.scrt to the main page of docs.scrt?

**Comment by dylanschultzie** [comment]
> @dylanschultzie I think we should set a redirect from learn.scrt to the main page of docs.scrt?

Yeah, I've asked @moonstash to wind down `learn.scrt.network` and redirect to `docs.scrt.network`. All the documentation from `learn` has been migrated already.

**Comment by reuvenpo** [comment]
awesome, that's great to hear :)

**Comment by DougAnderson444** [comment]
Thanks team! While I have your attention @dylanschultzie can you also ask @moonstash to also update the steps in:

[https://docs.scrt.network/dev/quickstart.html](https://docs.scrt.network/dev/quickstart.html)

According to the discord channel, I hit many outdated steps as I was working through it, and I saw others have also hit a level of frustration due to the steps being outdated (for example, how `secretcli` is now `secretd` in some parts, but `secretd` is never mentioned).

That would certainly help others just starting out.

**Comment by moonstash** [comment]
@DougAnderson444 I do not update the docs anymore at all. You will have to ping someone else.

I did turn off learn.scrt.network though.

**Comment by DougAnderson444** [comment]
Actually, the site I meant to mention is:

https://build.scrt.network/dev/quickstart.html#secret-contracts-quickstart

Which is `build.` subdomain and looks the same as `docs.` but the outdated info still seems to be there (too)?
