### ISSUE TITLE
secretcli query account balance error (testnet)

### ISSUE THREAD

**Issue by daviddemeij** [scrtlabs/SecretNetwork#840]
### Description
I have been going through the quickstart tutorial and it went smoothly until [here](https://build.scrt.network/dev/quickstart.html#get-some-scrt-from-the-faucett). After submitting my address to the faucet I try to obtain my account balance but I get the error below. This is probably a networking permission issue on my side, but it might be helpful to elaborate on how to avoid this in the quickstart docs.

Also I would suggest adding the `secretcli query account` command in the quickstart guide instead of only stating "Continue when you have confirmed your account has some SCRT in it."

### Steps to Reproduce
```
secretcli query account <secret address>
```
or 
```
secretcli --chain-id holodeck-2 query account <secret address>
```

**Expected behavior:**
Get the account balance.

**Actual behavior:**
```
ERROR: ABCIQuery: Post failed: Post "http://bootstrap.secrettestnet.io:26657": dial tcp 104.129.46.89:26657: connect: connection refused
```

**Comment by reuvenpo** [comment]
Hi @daviddemeij !
The guide there is a little outdated, sorry about that.
You can connect to the current testnet using:
```bash
secretcli config chain-id holodeck-2
secretcli config node 'https://chainofsecrets.secrettestnet.io:26667'
```
Using these, you don't have to use the `--chain-id` flag in your other commands

**Comment by daviddemeij** [comment]
> Hi @daviddemeij ! The guide there is a little outdated, sorry about that. You can connect to the current testnet using:
> 
> ```shell
> secretcli config chain-id holodeck-2
> secretcli config node 'https://chainofsecrets.secrettestnet.io:26667'
> ```
> 
> Using these, you don't have to use the `--chain-id` flag in your other commands

Thank you very much, that is very helpful! 

I am having another issue following this, when I try to get my account balance after I create a new account, it says my address does not exist. 
```
(base) david@david-ThinkPad-P50:~$ secretcli keys add david_test2

- name: david_test2
  type: local
  address: secret1cf6hskzq0822py633nrzxl06m2r4qlrq367z0m
  pubkey: secretpub1addwnpepqfsmf4ypc0jee3lvm2c2ge8sjp6rvrtpsrqh0u60zew95a6epfu8umf48t7
  mnemonic: ""
  threshold: 0
  pubkeys: []


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

innocent magnet announce tree romance pitch little robust very heavy robust erase spray fade account relax cable apple false abuse digital custom acquire cancel
(base) david@david-ThinkPad-P50:~$ secretcli query account secret1cf6hskzq0822py633nrzxl06m2r4qlrq367z0m
ERROR: unknown address: account secret1cf6hskzq0822py633nrzxl06m2r4qlrq367z0m does not exist
```

**Comment by reuvenpo** [comment]
This is correct. The account only exists on the chain after you've funded it. If you just generate it locally it doesn't register it on the chain. You'll have to get some SCRT sent to it. The faucet isn't working at the moment but if you join our discord server at https://chat.scrt.network you can ask for some testnet SCRT in the testnet channel.

**Comment by daviddemeij** [comment]
Ah okay, should I make a PR to update the docs a bit? Also fixing the other issue I created #839

**Comment by reuvenpo** [comment]
Yes, that would be very much appreciated!
We're launching a new chain in a couple days though so it'll be best to update the docs in a week or two after a new testnet has been started as well. You can start with a PR fixing the little errors, and we'll later patch up the docs to point to the newest testnet :)

**Comment by Cashmaney** [comment]
Closing this as I assume the docs have been updated by now
