### ISSUE TITLE
Error signing query permit using secretd

### ISSUE THREAD

**Issue by darwinzer0** [scrtlabs/SecretNetwork#853]
I noticed there is a new sw-dev docker image v1.2.0-1 that adds the sign-doc command from secretcli back into secretd: https://hub.docker.com/r/enigmampc/secret-network-sw-dev/tags

However, when I follow the SNIP-24 instructions to sign a query permit by the command line I am getting the following error:

```sh
root@f97aa9099b73:~# secretd tx sign-doc ./permit.json --from a > ./sig.json
panic: invalid character '}' looking for beginning of object key string

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*LegacyAmino).MustUnmarshalJSON(...)
    /go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.44.4-0.20211117100413-27366ad17d3a/codec/amino.go:171
github.com/cosmos/cosmos-sdk/x/auth/client/cli.readStdSignDocFromFile(0x7ffdcfc85772, 0xd, 0x14, 0x20, 0x244eac0, 0xc000e3c870, 0xc000612eb0, 0xb, 0x2431ec0, 0xc000e71050, ...)
    /go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.44.4-0.20211117100413-27366ad17d3a/x/auth/client/cli/tx_doc_sign.go:90 +0x1da
github.com/cosmos/cosmos-sdk/x/auth/client/cli.makeSignDocCmd.func1(0xc000598f00, 0xc000d91ce0, 0x1, 0x3, 0x0, 0x0)
    /go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.44.4-0.20211117100413-27366ad17d3a/x/auth/client/cli/tx_doc_sign.go:43 +0x166
github.com/spf13/cobra.(*Command).execute(0xc000598f00, 0xc000d91c80, 0x3, 0x3, 0xc000598f00, 0xc000d91c80)
    /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005edb80, 0x1eed8b5, 0xe, 0xc000041670)
    /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
    /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
    /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895
main.Execute(0xc0005edb80, 0x2431f20, 0xc00001d240)
    /go/src/github.com/enigmampc/SecretNetwork/cmd/secretd/root.go:150 +0x29c
main.main()
    /go/src/github.com/enigmampc/SecretNetwork/cmd/secretd/main.go:9 +0x2a
```

On Discord it was mentioned that a similar error happened before version 1.0.6 of secretcli. It looks like 1.0.6 was changed to use version `1.13.8` of go instead of `latest`, but I think the new version of the Makefile uses `1.15.15`: https://github.com/scrtlabs/SecretNetwork/blob/7c45ce653cd6cf29001da66aabb02f81f46a4c7b/Makefile#L122 

I dunno but maybe that's related to the issue?

**Comment by assafmo** [comment]
Hi, can you provide the `permit.json` file? I think it's malformed

**Comment by darwinzer0** [comment]
Omg, you are right! I had an extra trailing comma after the last field in "value". I must have looked over it 10 times before seeing that. Too much switching back and forth between javascript, rust, and json, I guess. :P

**Comment by darwinzer0** [comment]
The example on the SNIP-24 page has the error, too: https://github.com/SecretFoundation/SNIPs/blob/master/SNIP-24.md#secretcli

**Comment by darwinzer0** [comment]
I added a pull request: https://github.com/SecretFoundation/SNIPs/pull/24

**Comment by assafmo** [comment]
Thanks!
