### ISSUE TITLE
Error when importing secretJs to a ssr app at runtime

### ISSUE THREAD

**Issue by floAr** [scrtlabs/SecretNetwork#854]
While upgrading older apps to secret-4 I noticed an error:
Previouly (0.11.0) you could do  ` const { SigningCosmWasmClient } = await import("secretjs")` to grab secretJs at runtime within a server side rendered app (or any app on JAM stack for that case)
Since the upgrade to (0.17.3) this fails with `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prototype')`. Any leads where this might come from / what to do against it?

**Comment by assafmo** [comment]
Damn, this happens to me too! :laughing: 
Are you using vite or esbuild by any chance? It works with 0.16.5 but not with 0.17.3, I need to further investigate. :facepalm:

**Comment by floAr** [comment]
Yep I am using Vite in combination with SvelteKit. File in question: https://github.com/floAr/ScalingEth-Hack/blob/main/frontend/src/lib/modules/secret/secret-store.ts

Trying different things out myself but not even sure how to pinpoint the error

**Comment by assafmo** [comment]
Fixed with secretjs@0.17.4
