### ISSUE TITLE
README : every urls in Docs section are deadlink except one

### ISSUE THREAD

**Issue by n3wborn** [scrtlabs/SecretNetwork#869]
The only link still pointing somewhere is  [How to use SecretJS to develop Secret dApps](https://github.com/scrtlabs/secret-contracts-guide/blob/master/cosmwasm-js.md), every other point  to a "page not found"

**Comment by assafmo** [comment]
@n3wborn thanks for reporting!
Cc @dylanschultzie (https://github.com/scrtlabs/SecretNetwork/pull/864#issuecomment-1006335893)

**Comment by n3wborn** [comment]
If updating dead links mean using [https://docs.scrt.network](https://docs.scrt.network) instead, I can fix this if you want. In fact I'm already doing it but I wanted to be sure of this before making a PR. 

If yes, [backup-a-validator](https://docs.scrt.network/node-guides/backup/backup-a-validator.html) link can't be updated for the moment as also point to nowhere. Should I fill another issue for this one ?

**Comment by dylanschultzie** [comment]
> If updating dead links mean using https://docs.scrt.network instead, I can fix this if you want. In fact I'm already doing it but I wanted to be sure of this before making a PR.

Thanks!

**Comment by assafmo** [comment]
@n3wborn can we close this?

**Comment by assafmo** [comment]
Fixed, now just refers to https://docs.scrt.network.
