### ISSUE TITLE
bash: secretcli: command not found

### ISSUE THREAD

**Issue by elie222** [scrtlabs/SecretNetwork#872]
Hey,

Was just going through the getting started in the tutorial and ran into this issue:

```sh
docker exec -it secretdev /bin/bash

root@d9b8e8c407de:~# secretcli keys list --keyring-backend test
bash: secretcli: command not found
```

Here in the tutorial:
https://docs.scrt.network/dev/quickstart.html#setup-the-local-developer-testnet

**Comment by assafmo** [comment]
Thanks for reporting, will be fixed soon. In the meantime you just replace `secretcli` with `secretd`.
