### ISSUE TITLE
LocalSecret: Add secretcli binary

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/SecretNetwork#877]
See issue https://github.com/scrtlabs/SecretNetwork/issues/872

**Comment by RishiKumarRay** [comment]
That tutorial was not much clear, can you give any more references to solve this

**Comment by assafmo** [comment]
@RishiKumarRay see the docs for using LocalSecret https://docs.scrt.network/dev/LocalSecret.html

**Comment by assafmo** [comment]
Fixed in `ghcr.io/scrtlabs/localsecret:v1.3.0-beta.3`. Will update the docs after the mainnet upgrade on May 11
