### ISSUE TITLE
LocalSecret: Find a solution for Mac/AMD/ARM users 

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/SecretNetwork#878]
I'm thinking of maybe creating a docker images that runs QEMU and inside of QEMU run the current docker image.

**Comment by Photomen1** [comment]
#877

**Comment by faddat** [comment]
Doesn't this fail because no SGX?

**Comment by assafmo** [comment]
The local testnet docker is using SGX simulation mode, so it works without the actual hardware and without actually working on encrypted data. @Cashmaney reports that it's already working on his AMD machine, so IMO we just need to create an ARM build in Makefile like we have for the contract build optimizer.

**Comment by Cashmaney** [comment]
Does this issue refer to the actual localsecret docker image, or just the secretcli executable?

**Comment by assafmo** [comment]
Just the docker image. Being able to run it on Mac M1 for example.

**Comment by Cashmaney** [comment]
﻿Upon further investigation this _might_ ﻿be possible on M1 if the cross-compiled image is run on QEMU > 6.2 (https://www.phoronix.com/scan.php?page=news_item&px=QEMU-6.2-Released). From what I've seen, the default QEMU version for Docker Desktop on M1 is like 5.x.x which might explain why by default emulation isn't working.

It's also entirely possible this is futile and there really isn't a good way to get this to work. I'll continue to play around with this and update the issue if there is any progress made:(

**Comment by assafmo** [comment]
https://github.com/apache/incubator-teaclave-sgx-sdk/issues/318#issuecomment-998521315

**Comment by Cashmaney** [comment]
Okay, closing this for now since an intrim solution is available in the form of the Gitpod environment - https://docs.scrt.network/secret-network-documentation/development/tools-and-libraries/local-secret#start-localsecret
