### ISSUE TITLE
command no found: secretcli

### ISSUE THREAD

**Issue by baileyspraggins** [scrtlabs/SecretNetwork#885]
Hi I am trying to start developing dApps on secret and cant seem to install the secretcli. No matter which version I install when trying to configure the secretcli all I get is command not found: secretcli. I have followed the instructions line by line and have tried multiple versions as well.

**Comment by toml01** [comment]
Hi @baileyspraggins , sounds like your system is simply unable to find the `secretcli` binary.
What OS are you on?
This might help: https://codefather.tech/blog/linux-command-not-found/#:~:text=The%20%E2%80%9CCommand%20not%20found%E2%80%9D%20error%20is%20caused%20by%20the%20fact,without%20specifying%20its%20full%20path.

**Comment by baileyspraggins** [comment]
MacOs. Got the system to find it but now its saying permission denied when running the commands in terminal.

**Comment by baileyspraggins** [comment]
Fixed the issue
