### ISSUE TITLE
Use default TLS port when configuring CLI node

### ISSUE THREAD

**Issue by rigwild** [scrtlabs/SecretNetwork#908]
Hey,

When configuring the node to connect to with `secretcli` and not specifiying the port, it doesn't work. Maybe the 443 TLS port should be the default when it isnt specified and the protocol is `https`? 

```
$ secretcli config node https://secret-4--rpc--full.datahub.figment.io/apikey/123456789

$ secretcli status
Error: post failed: Post "https://secret-4--rpc--full.datahub.figment.io/apikey/123456789":
dial tcp: address secret-4--rpc--full.datahub.figment.io: missing port in address
```

The following currently works:

```
$ secretcli config node https://secret-4--rpc--full.datahub.figment.io:443/apikey/123456789
$ secretcli status
{"NodeInfo":{"protocol_version":...
```

**Comment by Cashmaney** [comment]
Thanks. This is mostly behaviour we inherit from the cosmos-sdk version we use. I tend to agree that it is more intuitive to use 443 for https (and probably 26657 for http). I'll look into this and see if we can throw it in a future version. Thanks for the suggestion
