### ISSUE TITLE
Application idea - Encrypted group messaging

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/SecretNetwork#91]
Encrypted group chat is created based on a secret contract, where messages coming from group members are stored in the secret contract state of Enigma blockchain. Using the concept of encrypted outputs, participants of the chat can access messages. 

This application requires an admin (Alice) and other users (Bob and Charlie), who participate in the encrypted messaging

- Alice (admin) creates a secret group chat room by deploying the secret contract
- Alice adds Bob and Charlie to the chat - there should be a function for access mgmt, where Alice can add Bob and Charlie's public keys - messages would be encrypted in a way such that Alice and Bob and Charlie are able to read
- Alice, Bob or Charlier can send messages to the secret contract, each message updates the contract state
- Alice, Bob and Charlie should be able to see the msg history through a GUI

Questions:
- Would it be possible to encrypt the output such that it can be decrypted by Alice, Bob and Charlie? One option is to encrypt the message n times, where n=3 in this case. Not elegant but would work 
- Would each chat need to be deployed as a new contract? If so is it going to be expensive for the users (lower priority)

**Comment by cankisagun** [comment]
Based on issue #201 , there doesn't seem to be any limitations with the encrypted group chat idea.

Once secret chat group (whitelist) is determined by the user who deploys the contract, she can define the addresses and any other msg_sender can be rejected to view / decrypt the data
@reuvenpo , what do you think?

**Comment by reuvenpo** [comment]
Yes, i don't think there will be a problem with this application. 
Reading the original description i was about to suggest how to simplify it, but you got the idea on your own :smile: 
I don't see a problem with having one contract manage an unbounded set of groups.
At the moment we do have a problem where a malicious host can provide outdated values to the contract for only some of the fields in storage, which creates what we call the "old permissions new secrets" and "old secrets new permissions". This needs to be solved by the contract logic itself, but is easy to do in most cases. In this application the risk is that a new member in a chat can view the entire chat history (in a very naive contract) or force an enclave to reveal old messages in the chats he is in (in a slightly less, but still naive contract). This might not be an issue at all, or just require careful permission design inside the contract itself. I can elaborate on this in private.

**Comment by cankisagun** [comment]
Potentially a way to change the group (add members) after it's created 
https://pegasys.tech/privacy-upgrades-for-hyperledger-besu-1-5/
