### ISSUE TITLE
Starshell wallet safe for all transactions 

### ISSUE THREAD

**Issue by Ediongdave** [scrtlabs/SecretNetwork#910]
The @StarShellWallet helps to protect your identity by limiting types of information dApps can collect about your accounts and it is an open source web3 wallet built for @SecretNetwork & cosmos ecosystem.
$SCRT $ATOM $LUNA.
@darwinzer0 
@lauraweindorf 
@lacabra 

https://twitter.com/StarShellWallet/status/1506038833795592193?t=iJbhvn3cVyIKQntMfVYaCA&s=19

**Comment by Ediongdave** [comment]
Sorry about the thread I will take it down rn.
Thankyou for the correction

**Comment by assafmo** [comment]
That's okay. It isn't really an issue or a bug report so I closed it.

**Comment by Ediongdave** [comment]
> That's okay. It isn't really an issue or a bug report so I closed it.

Alright.
