### ISSUE TITLE
Add support for CosmosMsg::Custom variant

### ISSUE THREAD

**Issue by mweichert** [scrtlabs/SecretNetwork#913]
This request comes from my strong desire to do IBC transfers from a Smart Contract. I realize that this is coming, but I wanted to dive into the code a bit to understand _why_ it's not possible now. After doing so, I think we should adjust how we handle the Custom variant of the CosmosMsg enum.

The wasmTypes.CosmosMsg type looks like this currently:
```
type CosmosMsg struct {
	Bank    *BankMsg        `json:"bank,omitempty"`
	Custom  json.RawMessage `json:"custom,omitempty"`
	Staking *StakingMsg     `json:"staking,omitempty"`
	Wasm    *WasmMsg        `json:"wasm,omitempty"`
	Gov     *GovMsg         `json:"gov,omitempty"`
}
```

After a smart contract is executed, the compute module dispatches all messages returned.

However, these messages are of the CosmosMsg type and need to be encoded as an SDK Msg type. This is done using MessageEncoders. The compute keeper has a list of default encoders for each type of CosmosMsg:
```
func DefaultEncoders() MessageEncoders {
	return MessageEncoders{
		Bank:    EncodeBankMsg,
		Custom:  NoCustomMsg,
		Staking: EncodeStakingMsg,
		Wasm:    EncodeWasmMsg,
		Gov:     EncodeGovMsg,
	}
}
```

Looking at the above, you can see that the Custom variant is encoded using the NoCustomMsg function, which simply throws an error:
```
func NoCustomMsg(sender sdk.AccAddress, msg json.RawMessage) ([]sdk.Msg, error) {
	return nil, sdkerrors.Wrap(types.ErrInvalidMsg, "Custom variant not supported")
}
```

Instead, why don't we create a MsgCustom type which implements the SDK Msg interface, and then write an EncodeCustomMsg function which accepts a Custom variant of the CosmosMsg type, and returns a MsgCustom type?

To implement the Msg interface, we have to implement two methods:
```
        // Msg defines the interface a transaction message must fulfill.
	Msg interface {
		proto.Message

		// ValidateBasic does a simple validation check that
		// doesn't require access to any other information.
		ValidateBasic() error

		// Signers returns the addrs of signers that must sign.
		// CONTRACT: All signatures must be present to be valid.
		// CONTRACT: Returns addrs in some deterministic order.
		GetSigners() []AccAddress
	}
```

For MsgCustom, ValidateBasic() could just return nil to accept any message, and GetSigners() could just return msg.sender.

This would open up advanced use cases for developers. For instance, if I wanted to do an IBC transfer from my smart contracts, I could just fork secret-cosmwasm-std and edit the Custom variant to accept a struct with fields that match the MsgTransfer struct used by IBC transfers:
https://github.com/cosmos/ibc-go/blob/v1.1.5/modules/apps/transfer/types/msgs.go

I'd be happy to create a PR for this kind of thing, but I have to assume that my naive understanding of things is why NoCustomMsg is used for encoding the Cosmog::Custom variant. Nonetheless, your response either way would help gap my knowledge in this area.

Thanks!

**Comment by assafmo** [comment]
Hi @mweichert, thanks for taking a look into this mechanism! We'll look into making it more usable. On our roadmap this year is an upgrade to CosmWasm v1 (we're on v0.10 now), so we'll see how it is there and what we can do to improve it further.
