### ISSUE TITLE
I get a "missing port in address" even when I clearly put a port number in the address for the secretd config rpc node

### ISSUE THREAD

**Issue by ChristianOConnor** [scrtlabs/SecretNetwork#915]
I got the following error:  
```
root@<MY DOCKER CONTAINER ID>:~/code# secretd config
{
        "chain-id": "pulsar-2",
        "keyring-backend": "test",
        "output": "json",
        "node": "https://secret-pulsar-2--rpc--full.datahub.figment.io/apikey/<MY API KEY>:443",
        "broadcast-mode": "sync"
}
root@<MY DOCKER CONTAINER ID>:~/code# secretd query bank balances <MY SECRET NETWORK ADDRESS>
Error: post failed: Post "https://secret-pulsar-2--rpc--full.datahub.figment.io/apikey/<MY API KEY>:443": dial tcp: address secret-pulsar-2--rpc--full.datahub.figment.io: missing port in address
root@<MY DOCKER CONTAINER ID>:~/code# 
```  

Notice that "https://secret-pulsar-2--rpc--full.datahub.figment.io/apikey/<MY API KEY>:443" clearly specifies port 443. The error shows that it clearly cuts everything off after the `.io`

**Comment by levackt** [comment]
It should be domain:port, so try "secretd config node https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/<MY API KEY>"

**Comment by reuvenpo** [comment]
Unfortunately, The Cosmos SDK, which `secretd` and `secretcli` are built on, does not support authentication with an API key the way that Figment requires... Getting this to work will require some work upstream.

**Comment by levackt** [comment]
Their request works @reuvenpo 

`root@secretdev:~# 
secretd config node https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/MY_KEY

secretd config node https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/MY_KEY

root@secretdev:~# secretd config
{
	"chain-id": "pulsar-2",
	"keyring-backend": "test",
	"output": "json",
	"node": "https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/MY_KEY",
	"broadcast-mode": "sync"
}

root@secretdev:~# secretd query bank balances secret1t4crj8yjgwe0dmv2fzvf4jlc6se0amz07afs7c

{"balances":[{"denom":"uscrt","amount":"320903711578182044"}],"pagination":{"next_key":null,"total":"0"}}
root@secretdev:~#`

**Comment by reuvenpo** [comment]
Oh this is new to me! Cool!

**Comment by ChristianOConnor** [comment]
> Unfortunately, The Cosmos SDK, which `secretd` and `secretcli` are built on, does not support authentication with an API key the way that Figment requires... Getting this to work will require some work upstream.

Oh really? Is there another API provider I can use for Secret Network?

**Comment by ChristianOConnor** [comment]
> Their request works @reuvenpo
> 
> `root@secretdev:~# secretd config node https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/MY_KEY
> 
> root@secretdev:~# secretd config { "chain-id": "pulsar-2", "keyring-backend": "test", "output": "json", "node": "https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/MY_KEY", "broadcast-mode": "sync" }
> 
> root@secretdev:~# secretd query bank balances secret1t4crj8yjgwe0dmv2fzvf4jlc6se0amz07afs7c
> 
> {"balances":[{"denom":"uscrt","amount":"320903711578182044"}],"pagination":{"next_key":null,"total":"0"}} root@secretdev:~#`

Whoa! How did you get it to work? What are you doing differently?

**Comment by levackt** [comment]
> Whoa! How did you get it to work? What are you doing differently?

I posted the config command, please see if that works for you, or if you get a new error.
The only other thing I can note, is that my docker image is the latest enigmampc/secret-network-sw-dev

**Comment by ChristianOConnor** [comment]
> > Whoa! How did you get it to work? What are you doing differently?
> 
> I posted the config command, please see if that works for you, or if you get a new error. The only other thing I can note, is that my docker image is the latest enigmampc/secret-network-sw-dev

I made my config look like yours and it worked!! Thank you so much!
