### ISSUE TITLE
I get "Error: illegal base64 data at input byte 0" when trying to instantiate NFT contract

### ISSUE THREAD

**Issue by ChristianOConnor** [scrtlabs/SecretNetwork#916]
I have been following https://docs.scrt.network/dev/quickstart.html#create-initial-smart-contract perfectly and I'm stuck at initializing a smart contract. I used this snip-721 boilerplate https://github.com/baedrik/snip721-reference-impl.git. I was able to compile and store it perfectly on the pulsar-2 testnet. Everything was working great until I got to initializing the contract.  

I ran `INIT='{"name":"TestWasOne","symbol":"TeWo","entropy":"<RANDOM STRING>","config":{"public_owner":true}}'`, then `CODE_ID=<MY CONTRACT'S CODE_ID>`, and finally `secretd tx compute instantiate $CODE_ID "$INIT" --from mainkey --label "TestWasOne NFT" -y` and I got this error:  
```
Failed to get IO key. Make sure the CLI and the node you are targeting are operating in the same SGX mode
2022/04/11 01:31:25 illegal base64 data at input byte 0
Error: illegal base64 data at input byte 0
```  

I know my account "mainkey" has my compiled `https://github.com/baedrik/snip721-reference-impl.git` instance compiled and stored perfectly. What do you think the problem is?

**Comment by toml01** [comment]
Are you running this on a local node?
Try running `secretd` like this:
`SGX_MODE=SW secretd tx ..`

**Comment by ChristianOConnor** [comment]
> Are you running this on a local node? Try running `secretd` like this: `SGX_MODE=SW secretd tx ..`

No I'm connected to pulsar-2 this is the output of `secretd config`:  
```
{
        "chain-id": "pulsar-2",
        "keyring-backend": "test",
        "output": "json",
        "node": "https://secret-pulsar-2--rpc--full.datahub.figment.io:443/apikey/<MY API KEY>",
        "broadcast-mode": "sync"
}
```  

I tried `SGX_MODE=SW secretd tx compute instantiate $CODE_ID "$INIT" --from mainkey --label "TestWasOne NFT" -y` but I got the error

**Comment by assafmo** [comment]
When you run `secretd status`, looking at the `latest_block_time`, is it current or lagging?

**Comment by ChristianOConnor** [comment]
I fixed it thanks to a helpful Discord user! I ran `export SGX_MODE=HW` and all of a sudden `secretd tx compute instantiate $CODE_ID "$INIT" --from mainkey --label "TestWasOne NFT" -y` worked!

**Comment by assafmo** [comment]
Amazing! Thanks for circling back to close the issue. :hearts:
