### ISSUE TITLE
The Only snip721 Reference Implementation I Could Find Is GPL-3.0 Licensed, Do my NFTs and Dapps Accessing Them Have to Be Open Source?

### ISSUE THREAD

**Issue by ChristianOConnor** [scrtlabs/SecretNetwork#917]
Hey I just realized that the snip721 reference implementation I've been using, https://github.com/baedrik/snip721-reference-impl, is GPL-3.0 licensed. Does that mean that any NFT I implement with this repo has to have the same license? Like if I made a cool 3D art file that was in any way code generated, would I have to release the source code? Also, I use a svelte frontend for an NFT minting dapp similar to the code in this repo https://github.com/floAr/FigmentLearn-FromZeroToYourFirstSecretNFT. Does that mean I have to make my whole dapp open source becuse I used https://github.com/baedrik/snip721-reference-impl to make the actual NFTs?

If this does mean that my NFTs and frontend dapps that interact with them have to be open sourced, is there any other snip721 reference implementation that is MIT, APACHE, or BSD licensed or licensed by some other less restrictive open source license that I can use for my snip721?

**Comment by assafmo** [comment]
You should ask in https://github.com/baedrik/snip721-reference-impl for clarifications. IANAL, but IMO the UI is not a derivative of the contract code, thus not bound by the SNIP-721 reference implementation license.
