### ISSUE TITLE
Error: post failed ... connect: connection refused

### ISSUE THREAD

**Issue by Ripple-activator** [scrtlabs/SecretNetwork#920]
Thanks for reporting, will be fixed soon. In the meantime you just replace `secretcli` with `secretd`.

_Originally posted by @assafmo in https://github.com/scrtlabs/SecretNetwork/issues/872#issuecomment-1012380109_

Command: 
secretd tx compute store contract.wasm.gz --from a --gas 1000000 -y --keyring-backend test

Answer: 
Error: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused

**Comment by reuvenpo** [comment]
Are you trying to use the local docker testing environment, or the testnet?

If trying to use the local docker testing environment, did you start it? You can do that by running this command in a separate terminal:
```bash
docker run -it --rm \
	-p 9091:9091 -p 26657:26657 -p 26656:26656 -p 1317:1317 -p 5000:5000 \
	-v $$(pwd):/root/code \
	--name secretdev enigmampc/secret-network-sw-dev:v1.2.6
```

If you are trying to connect to the testnet, you'll need to run these commands with valid network parameters first:
```bash
secretcli config chain-id $CHAIN_ID # e.g. pulsar-2
secretcli config node $NODE_URL # https://some.domain:26657
```
The `pulsar-2` testnet is under maintenance at the moment so I don't think there's an available node you can connect to at the moment.

**Comment by Ripple-activator** [comment]
> 

I follow the instructions from [here](https://build.scrt.network/dev/quickstart.html#setup-the-local-developer-testnet).

Instead of written there:
`docker run -it --rm \
		 -p 26657:26657 -p 26656:26656 -p 1337:1337 \
 		-v $(pwd):/root/code \
		 --name secretdev enigmampc/secret-network-sw-dev`

I entered what you wrote:
`docker run -it --rm \
		-p 9091:9091 -p 26657:26657 -p 26656:26656 -p 1317:1317 -p 5000:5000 \
		-v $(pwd):/root/code \
		--name secretdev enigmampc/secret-network-sw-dev:v1.2.6`

Here's [what happened](https://imgur.com/a/qBo9Eyk).

In the new terminal, I enter alternately:
`cd C:\Users\admin\mysimplecounter
docker exec -it secretdev /bin/bash
cd code
secretd config node https://secretnodes.com/secret/chains/pulsar-2:26657
secretd config keyring-backend test
secretd config chain-id https://chainofsecrets.secrettestnet.io:26667
secretd config trust-node true
Error: unknown configuration key: "trust-node"
secretd tx compute store contract.wasm.gz --from a --gas 1000000 -y --keyring-backend test
Error: post failed: Post "https://secretnodes.com/secret/chains/pulsar-2:26657" dial tcp: address secretnodes.com: missing port in address`

I downloaded the secretcli file to the mysimplecounter folder [from here](https://github.com/scrtlabs/SecretNetwork/releases/tag/v1.2.2), specified the PATH path – the secretcli command does not work anyway. Is the secretcli 1.2.2 version exactly right?

I work in Docker, could you write down in steps what needs to be done at the moment when Pulsar-2 is not working? Where and what kind of addresses should I specify? In what order should I enter commands so that everything works without errors?

**Comment by reuvenpo** [comment]
There are a few issues with what you did above:

- when running `secretd config node`, the URL your provided is a URL to the explorer, not to an actual node. You should use `rpc.pulsar.griptapejs.com](https://rpc.pulsar.griptapejs.com/` instead.

- The commands in the docker seem to be crashing with no explanation. What CPU, operating system, and docker version are you using?

**Comment by reuvenpo** [comment]
I see... The docker images require an intel CPU from generation 6 and above. Your CPU seems to be a very very old one, from the gen-2 series (Indicated by the first 2 in "2320"). You'll need a newer machine to run the local docker environment successfully.

**Comment by Ripple-activator** [comment]
> I see... The docker images require an intel CPU from generation 6 and above. Your CPU seems to be a very very old one, from the gen-2 series (Indicated by the first 2 in "2320"). You'll need a newer machine to run the local docker environment successfully.

There is an Intel Core i3-9100T minicomputer (3.1 GHz), 4 GB RAM, 480 GB SSD, Intel HD Graphics 630. Will it do? Which OS is better to put there? Ubuntu?

**Comment by reuvenpo** [comment]
it should work well with ubuntu, yes

**Comment by deployAt** [comment]
Hey, same issue on Macbook (not M1), any ideas?

```bash
~ docker run -it --rm \
	-p 9091:9091 -p 26657:26657 -p 26656:26656 -p 1317:1317 -p 5000:5000 \
	-v $(pwd):/root/code \
	--name secretdev enigmampc/secret-network-sw-dev:v1.2.6
...
...
...

2:56PM INF starting ABCI with Tendermint
bootstrap: true2022-04-28 14:56:53,211 INFO  [cosmwasm_sgx_vm::enclave] Setting up enclave doorbell for up to 1 threads
[2022-04-28 14:56:53 +0000] [178] [INFO] Starting gunicorn 20.1.0
[2022-04-28 14:56:53 +0000] [178] [INFO] Listening at: http://0.0.0.0:5000 (178)
[2022-04-28 14:56:53 +0000] [178] [INFO] Using worker: sync
[2022-04-28 14:56:53 +0000] [191] [INFO] Booting worker with pid: 191

 Proxy Active

Proxy Url: http://localhost:1317
Proxy Partial:
PORT: 1337
Credentials: false
Origin: *

To start using the proxy simply replace the proxied part of your url with: http://localhost:1337/

./bootstrap_init.sh: line 63:   179 Killed                  RUST_BACKTRACE=1 secretd start --rpc.laddr tcp://0.0.0.0:26657 --bootstrap
[2022-04-28 14:57:01 +0000] [178] [INFO] Handling signal: winch
[2022-04-28 14:57:02 +0000] [178] [INFO] Handling signal: winch
```



```bash
~ docker exec -it secretdev /bin/bash
root@60b61d4aeba0:~# cd code
root@60b61d4aeba0:~/code#
root@60b61d4aeba0:~/code# secretd tx compute store contract.wasm.gz --from a --gas 1000000 -y --keyring-backend test
Error: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused
```

**Comment by reuvenpo** [comment]
Yup, ARM CPUs such as the Apple M1 are also not supported yet.

**Comment by Ripple-activator** [comment]
> 

Hello again. Step: 
`cargo install cargo-generate --features vendored-openssl`

[Error](https://imgur.com/a/rcvDDKO):
`error: MaybeUninit::<T>::assume_init is not yet stable as a const fn
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/kstring-2.0.0/src/string.rs:844:17
    |
844 |                 std::mem::MaybeUninit::uninit().assume_init()
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: could not compile `kstring` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-installkrDo6d`
Caused by:
  build failed`

**Comment by reuvenpo** [comment]
This is an unrelated issue, so better if you open it separately, or just asked in the forum or discord.
I'm closing this issue for now because we don't have a solution for it right now :(

**Comment by Ripple-activator** [comment]
> This is an unrelated issue, so it's better if you open it separately, or just asked in the forum or discord. I'm closing this issue for now because we don't have a solution for it right now :(

What is the command for the execution of the "Mysimplecounter" smart contract in the Pulsar-2 test network?

When studying in Docker, it looks like this:

`secretd tx compute execute $CONTRACT '{"increment": {}}' --from a --keyring-backend test`

It does not with secretcli when the contract loaded in Pulsar-2.

**Comment by assafmo** [comment]
https://github.com/scrtlabs/SecretNetwork/issues/878
