### ISSUE TITLE
Interacting with the secret network.

### ISSUE THREAD

**Issue by FormidablePencil** [scrtlabs/SecretNetwork#940]
How would I interact with the secret network from my rust project. Is there a client or something for this?

**Comment by assafmo** [comment]
Hi, more details would help us help you, but generally there are a few options.

1. You can use the REST API, here's the available endpoints: https://api.roninventures.io/swagger/
2. You can derive gRPC services from the protobuf definitions and use it with a gRPC or gRPC-web crate to interact with the chain. Here's how we derive gRPC-web services for Typescript: https://github.com/scrtlabs/secret.js/blob/master/scripts/generate_protobuf.sh

**Comment by FormidablePencil** [comment]
I really like the project. An optionally private smart contract state is a no brainer yet there are very few who are doing this. I guess only a few see the true picture of potential in the web3 and not merely just shinny transient things like NFTs. I'm building a out a social utility of sorts. I've opted for Rust + Flutter together as a dapp for cross platform purposes. Thanks for the you helps. I think I got it from here.

**Comment by assafmo** [comment]
Cool, we're on Discord at https://chat.scrt.network for a more interactive support.

**Comment by FormidablePencil** [comment]
> I've been wondering about how to make a Rust version of secret.js, but wasn't sure how useful it would be to create and/or maintain.

Since rust is the main language for blockchains in writing smart contract because of being a low level language, feature rich and relatively easy to use and compiles down to webassembly for web apps. I see rust being a go to language for most purposes or at least should be in my humble opinion. It simply is most convenient to write business logic once and use it across all platforms without relying on cross platform frameworks. All languages, tool and frameworks are only valuable for their utility. Rust has the greatest versatility and rich in features and design. As dapps begin to arise in offering a more secure and fair alternative to the current society dependent utilities and platforms the more Rust will be recognized for it will be an obvious choice in developing smart contract which aim to be as compact and performant as possible to reduce transaction fees as much as it can.

I'm in the process of mapping everything out with what I'm trying to build but when I get around in experimenting with Secret Network smart contracts I let you know what I think about a rust implementation of client.

**Comment by chris-ricketts** [comment]
@FormidablePencil I've made a start along these lines with this crate: https://github.com/chris-ricketts/localsecret-rs

It contains a client that connects over Tendermint RPC to the node running inside the LocalSecret docker container (software SGX). Currently this serves my use case to do on-chain integration tests from Rust without shelling out to `secretcli`.

The aim is to extract the client into it's own crate and make it configurable at runtime to connect to any mainnet or public testnet version of SecretNetwork. The main addition required to enable this is to retrieve the enclave io public key from hardware SGX nodes when not it "testing" mode which is a slightly different process to 'software' SGX enclaves.

**Comment by FormidablePencil** [comment]
I applaud you @chris-ricketts .
I'm not focused on any implementation details in relation to Secret Network anytime soon (but time flies, I'll get around to it relatively soon 😉). There's a great potential use for rust based packages for the web3 world given rust code can be used in virtually all platforms; android, web, ios, etc. Its lightweightness is most beneficial in web3 where edge computing will be more prominent as well as the fact that rust seems to be a standard language for blockchain powered code for obvious reasons.
