### ISSUE TITLE
Port dev image faucet from python to node

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#957]
There's no real point to using a python-based faucet, since we already have node as part of the dev image, so this just makes compile times longer.

Faucet code is found here: https://github.com/scrtlabs/SecretNetwork/tree/master/deployment/docker/devimage/faucet

It's a simple REST service that gets pinged on port 5000 with an address and it sends 100 SCRT or something using the CLI

**Comment by levackt** [comment]
Any help wanted or is someone already working on this? @Cashmaney 

Happy to pick it up, just made a simple [UI for LocalSecret based private testnet](https://ui.scrttestnet.com/faucet), and wouldn't mind having a /status endpoint to go with it.

**Comment by Cashmaney** [comment]
@levackt go for it:)
